apiVersion: v1
kind: Pod
metadata:
  name: bad-kubesrv
  labels:
    app: kubesrv
    owner: demo
spec:
  containers:
    - name: kubesrv
      image: bansikah/kubesrv:1.0.0
      ports:
        - containerPort: 80
      securityContext:
        privileged: true
        runAsUser: 0