apiVersion: v1
kind: Pod
metadata:
  name: good-kubesrv
  labels:
    app: kubesrv
    owner: demo
spec:
  containers:
    - name: kubesrv
      image: bansikah/kubesrv:latest
      ports:
        - containerPort: 80
      resources:
        requests:
          cpu: 100m
          memory: 128Mi
        limits:
          cpu: 200m
          memory: 256Mi
      securityContext:
        privileged: false
        runAsNonRoot: true
        runAsUser: 1000
        allowPrivilegeEscalation: false
        readOnlyRootFilesystem: true